name: Holonbot CI

on:
  push:
    paths:
      - 'holonbot/**'
  pull_request:
    paths:
      - 'holonbot/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./holonbot

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: holonbot/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
